"""empty message

Revision ID: de815072ef2a
Revises: 
Create Date: 2024-09-30 14:58:01.354794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de815072ef2a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### создаем таблицу electives ###
    op.create_table(
        'electives',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('elective_type', sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    # ### создаем таблицу reviews ###
    op.create_table(
        'reviews',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('elective_id', sa.Integer(), nullable=False),
        sa.Column('user_name', sa.String(length=255), nullable=False),
        sa.Column('text', sa.Text(), nullable=False),
        sa.Column('date_created', sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(['elective_id'], ['electives.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
